/* The original 90-day shakedown punch list — inserted once when the database is empty. */
export const SEED = [
  { n: 1,  x: 129, y: 52,  loc: "Left bed — small window", desc: "Insulation falling out of the window frame.", safety: false },
  { n: 2,  x: 676, y: 322, loc: "Entry door steps", desc: "The latch doesn't grab the bottom step, leading to the step falling out.", safety: true },
  { n: 3,  x: 648, y: 350, loc: "Under entry steps", desc: "Rust on the frame.", safety: false },
  { n: 4,  x: 103, y: 350, loc: "Leg extension switches", desc: "Rust on the screws.", safety: false },
  { n: 5,  x: 706, y: 300, loc: "Screen door handle", desc: "Screen door handle is loose.", safety: false },
  { n: 6,  x: 40,  y: 350, loc: "Stabilizer", desc: "Stabilizer gets cut because it gets smashed.", safety: true },
  { n: 7,  x: 598, y: 350, loc: "Frame (step area)", desc: "The frame toes out in this area — bent compared to the other side.", safety: true },
  { n: 8,  x: 566, y: 78,  loc: "Kitchen cabinet next to stove", desc: "Finishing strip on cabinet is misaligned.", safety: false },
  { n: 9,  x: 508, y: 60,  loc: "Cabinet next to fridge", desc: "Loose screws, felt fell off, and the shelf wobbles.", safety: false },
  { n: 10, x: 902, y: 178, loc: "Front frame (A-frame)", desc: "Caulking is bad / failing.", safety: false },
  { n: 11, x: 938, y: 148, loc: "Propane line routing", desc: "Should the propane line run here? Concern the cable rubs against a sharp edge of the frame.", safety: true },
  { n: 12, x: 790, y: 112, loc: "Behind couch", desc: "Missing cap on opening behind the couch.", safety: false },
  { n: 13, x: 748, y: 66,  loc: "Over-couch left cabinet door", desc: "No clear coat — rough to the touch compared to the other doors.", safety: false },
  { n: 14, x: 478, y: 92,  loc: "Refrigerator bottom door", desc: "Doesn't latch — bottom right corner needs to be lifted to close.", safety: false },
  { n: 15, x: 142, y: 278, loc: "Passenger-side twin bed cabinet panel", desc: "Aluminum sheet is sticking out.", safety: false },
  { n: 16, x: 714, y: 42,  loc: "Front left speaker cabinet", desc: "Possible mold on the batting — please inspect. Many wires back there are not connected; verify and reconnect.", safety: true },
  { n: 17, x: 690, y: 182, loc: "Behind main TV", desc: "No rubber grommet on the hole where electrical wires pass through.", safety: false },
  { n: 18, x: 556, y: 104, loc: "Under oven + multiple exterior spots", desc: "Sealant has come loose under the oven and in multiple spots around the outside of the camper.", safety: false },
  { n: 19, x: 300, y: 26,  loc: "Roadside storage", desc: "Sharp burrs on metal edges — please deburr.", safety: false },
  { n: 20, x: 300, y: 348, loc: "Curbside storage", desc: "Left latch doesn't work.", safety: false },
  { n: 21, x: 938, y: 208, loc: "Propane tank area", desc: "Propane smell in the tank area — please leak-test the full LP system.", safety: true },
  { n: 22, x: 470, y: 26,  loc: "Front left wheel — Tow Assist sensor", desc: "Dexter Tow Assist (anti-sway/ABS) reports a fault in the front left wheel speed sensor. Please inspect sensor, tone ring, and wiring to ECU.", safety: true },
  { n: 23, x: 158, y: 96,  loc: "Left bed", desc: "Wood strip is coming off the bed frame.", safety: false },
];
